#!/bin/bash
############## SETUP VARIABLES ###########################################################
allelicCountFile=$1

copyNumberFile=$2

outDir=$3

installDir=/usr/local/APOLLOH_0.1.1/

mcrDir=/opt/MATLAB/MATLAB_Component_Runtime/v77

export LD_LIBRARY_PATH=$mcrDir/runtime/glnxa64/:$mcrDir/sys/os/glnxa64:$mcrDir/bin/glnxa64:$LD_LIBRARY_PATH

############## EXECUTE APOLLOH ##########################################################
#########################################################################################
#Arguments:
#1) Tab-delimited input file containing allelic counts from the tumour at positions determined as heterozygous from the normal genome
#2) Tab-delimited input copy number segment prior file. The accepted format is the output from HMMcopy, a read-depth for analyzing copy number in tumour-normal sequenced genomes.
#3) Parameter intialization file is a matlab binary (.mat) file. This file contains model and setting paramters necessary to run the program.
#4) Tab-delimited output file for position-level results.
#5) Tab-delimited output file storing converged parameters after model training using Expectation Maximization (EM) algorithm.
$installDir/bin/apolloh $allelicCountFile $copyNumberFile $installDir/parameters/apolloh_K18_params_SOLiDskew_stromalRatio_Hyper10k.mat $outDir/params.txt $outDir/loh.txt

############## Sort the output file by chromosome and position ##########################
############## We are performing numeric sorting on 1st (Chr) and 2nd (Position) columns.
############## Then we are assigning it to a temporary file.  Finally, we ###############
##############    overwrite our original file. ##########################################
sort -k1,1n -k2,2n $outDir/loh.txt > $outDir/loh.txt.tmp
mv $outDir/loh.txt.tmp $outDir/loh.txt

############## Create a segment file from the output file using a perl script ###########
############## -i option is the "input file" which should be the position-level #########
##############     output file generated by APOLLOH (*loh.txt) ##########################
############## -o option is the output filename #########################################
############## -calls option - just use 1. ##############################################
/usr/local/APOLLOH_0.1.1/scripts/createSingleSegFileFromAPOLLOH.pl -i $outDir/loh.txt -o $outDir/segs.txt -calls 1


